# Generated by Django 4.2.16 on 2024-09-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_dharma", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anomaly",
            options={"verbose_name_plural": "Anomalies"},
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="model_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
